name: Build, Test, and Push Docker Image
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test
        run: |
          test -f site/index.html || exit 1
          test -f site/style.css || exit 1
      - name: Build and Push
        run: |
          docker build -t docker.io/rudesandwich/my-static-site-two:latest .
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push docker.io/rudesandwich/my-static-site-two:latest